version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../../backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - ../../frontend/.env
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 