version: '3.8'

services:
  backend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../../backend/.env
    volumes:
      - ../../backend:/app
      - uploads:/app/uploads
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: ["npm", "start"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  uploads: 